# Generated by Django 3.2 on 2021-04-07 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('console', models.TextField()),
                ('releaseDate', models.DateField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gameCollections.genre')),
            ],
            options={
                'verbose_name_plural': 'games',
            },
        ),
    ]
