# Generated by Django 3.2 on 2021-04-13 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gameCollections', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='pizza',
            new_name='genre',
        ),
    ]
